
ports:
  - port: 7000-9999
    onOpen: open-browser
    visibility: public

tasks:
  - init: |
      npm install -g generator-jhipster
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-spring-boot-dashboard
